name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: FrancoGL/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
        # Display
          config_display: columns
        # Options
          user: FrancoGL
          template: classic
          base: ""
          config_timezone: America/Buenos_Aires
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # ISO Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # AniList
          plugin_anilist: yes
          plugin_anilist_user: Daletkiel
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, reading, characters
          plugin_anilist_limit: 4
          # Order
          config_order: isocalendar, achievements, anilist
