name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Medias
        if: ${{ success() || failure() }}
        uses: FrancoGL/metrics@master
        with:
          filename: medias.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: Daletkiel
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, reading, characters
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22
      
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEV_CARD_ID }
          
      #- name: Achievements
        #if: ${{ success() || failure() }}
        #uses: FrancoGL/metrics@master
        #with:
          #filename: achievements.svg
          #token: ${{ secrets.METRICS_TOKEN }}
          #base: ""
          #plugin_achievements: yes
          #plugin_achievements_display: compact
          #plugin_fortune: yes


      - name: General
        if: ${{ success() || failure() }}
        uses: FrancoGL/metrics@master
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
